### ISSUE TITLE
examples can't find files/directories under tempdir

### ISSUE THREAD

**Issue by yurivict** [QEF/q-e#11]
I am trying to run all examples using /tmp as a tempdir.
Some examples print such errors:
```
cp: /tmp/feo_af.occup: No such file or directory
```

```
create SOC folders and copy there SR density and spin moment...cp: /tmp/sr.save/spin-polarization.dat: No such file or directory
cp: /tmp/sr.save/spin-polarization.dat: No such file or directory
```

**Comment by giannozz** [comment]
With the old file format, spin polarization is in a separate file (it is no longer with the new format). The copy ensures that the example works with both formats. Will be removed soon together with the old format.
