### ISSUE TITLE
.dyn files

### ISSUE THREAD

**Issue by emiliosca** [QEF/q-e#16]
I think there is a problem in  PH.x, when writing the .dyn files. The celldm is not correct in the files....

**Comment by giannozz** [comment]
Please explain what is not correct under which circumstances and for which version

**Comment by emiliosca** [comment]
v.6.3, with ibrav=0, the cell parameter printed in the *.dyn file is != than the celldm in the scf input file. Then, obviously,  there is also a problem with dynmat.x which reads a wrong cell parameter and (for instance) also the asr is not correctly applied.
P.S. Same inputs with v.6.2 are working correctly for me.
Thanks

**Comment by giannozz** [comment]
Please report this issue on gitlab.org, with inputs for scf and for phonon that can be run. A fsimple test doesn't show anything strange:

 &system
    ibrav = 0, celldm(1) =10.20, nat=  2, ntyp= 1,  ecutwfc = 18.0
 /
[...]
CELL_PARAMETERS alat
0.5 0.5 0.0
0.5 0.0 0.5
0.0 0.5 0.5

Dynamical matrix file
phonons of Si at Gamma                                                     
  1    2  0 10.2000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000
Basis vectors
      0.500000000    0.500000000    0.000000000
      0.500000000    0.000000000    0.500000000
      0.000000000    0.500000000    0.500000000
