### ISSUE TITLE
multi-threaded make

### ISSUE THREAD

**Issue by colleenRooney** [QEF/q-e#17]
It seems like building this software doesn't play nice with the -j make flag. It took me a few builds to realize what was going wrong. Might be nice to add a quick note that using this flag will cause the build to fail in the documentation, if you all think that is appropriate. 

What I ran:
`./configure --prefix=/path/to/install --exec-prefix/path/to/install
make all -j8`

Results:
only the following executables were built: 
`iotk  iotk_print_kinds.x  iotk.x`

As an aside, it doesn't seem to me that the --exec-prefix flag does anything. Am I wrong in assuming this? (sorry if this is the wrong place to ask this)

**Comment by giannozz** [comment]
Please submit issues on gitalb (github is a mirror) and specify which version you are referring to. I have spent a considerable amount of time fixing make -j and as far as I know it works in both the development version and in qe-6.3-backports.
