### ISSUE TITLE
Build fails on ppc64

### ISSUE THREAD

**Issue by pkubaj** [QEF/q-e#18]
I'm trying to build for FreeBSD/powerpc64 platform. The problem is that vector is a keyword there (related to Altivec) and `-traditional` switch to cpp makes gcc treat vector word in comments as code. Changing e.g. G-vector to Gvector, or putting #if 0 around those comments helps, but that is obviously undoable for the whole project.

Build log:
https://talos.anongoth.pl/data/powerpc64-default/2019-02-05_05h49m32s/logs/errors/quantum-espresso-6.3_5.log

**Comment by giannozz** [comment]
You should first of all verify whether external preprocessing is really needed. Almost all compilers can do C-style preprocessing internally (for some cases it doesn't work, though). 
Please submit issues to gitlab: this is a mirror
