### ISSUE TITLE
Problem with XANES without core hole

### ISSUE THREAD

**Issue by JohnChueh** [QEF/q-e#2]
Hello, I am new to use QE. I followed a tutorial PPT online and calculated XANES with Xspectra. However, the result is that XANES without core hole effect is the same as XANES with core hole effect. 
Is there anyone can help me figure out how to solve this problem?

**Comment by giannozz** [comment]
Would you please explain whether this issue is solved or not?

**Comment by JohnChueh** [comment]
I have solved. It's my problem. I gave the wrong prefix name in *
xspectra.in file. Thanks for your concern.

giannozz <notifications@github.com> 於 2018年5月17日 週四 下午7:36 寫道：
