### ISSUE TITLE
compile  v6-4-1 by intel parallel studio 2018

### ISSUE THREAD

**Issue by mersadkhan** [QEF/q-e#20]
linux mint-19-1. I use below command to configure 
`./configure AR=xiar  FC=mpiifort CC=mpiicc F90=mpiifort  F77=mpiifort MPIF90=mpiifort  MPICC=mpiicc CXX=mpiicpc MPICXX=mpiicpc  --prefix=/opt/quantumespresso/6.4 --with-scalapack=intel  --enable-openmp`

"make all" give blow error 

`In file included from eval_infix.c(51):
/opt/intel/compilers_and_libraries_2018.1.148/linux/compiler/include/math.h(1336): error: identifier "_LIB_VERSION_TYPE" is undefined
  _LIBIMF_EXT _LIB_VERSIONIMF_TYPE _LIBIMF_PUBVAR _LIB_VERSIONIMF;
              ^

compilation aborted for eval_infix.c (code 2)
../make.inc:24: recipe for target 'eval_infix.o' failed
make[1]: *** [eval_infix.o] Error 2
make[1]: Leaving directory '/home/shrz/softs/q-e-qe-6.4.1/clib'
Makefile:213: recipe for target 'libs' failed
make: *** [libs] Error 1`

the same error appear when I use the patch file.

**Comment by giannozz** [comment]
It's not a problem of QE but of a C include file: I think there is something weird in your C compiler. Try to use gcc instead of icc
