### ISSUE TITLE
gipaw 6.4.1

### ISSUE THREAD

**Issue by sbecuwe** [QEF/q-e#23]
When building QE 6.4.1 with gipaw, the installation automatically wants to download https://github.com/dceresoli/qe-gipaw/archive/6.4.1.tar.gz
The most recent version of gipaw seems to be 6.3.
What's the best solution to get gipaw support in QE 6.4.1? Modifying the gipaw block in `install/plugins_list` and replacing `$(RELEASE_VERSION)` by 6.3?

Thanks!

**Comment by giannozz** [comment]
The best solution is to bug Davide Ceresoli until he acts. Alternatively, you may download a previous GIPAW version and make the few needed changes (basically, move around or remove a few variables) so that it compiles.

**Comment by giannozz** [comment]
(issues and bug reports please to gitlab.com)
