### ISSUE TITLE
Adding fftw3 to configure script

### ISSUE THREAD

**Issue by dishu1** [QEF/q-e#28]
Hello, can you, please, add an option into the configure script for configuring QE with fftw3 explicitly without autodetection? Since fftw3 on supercomputers is installed as a module, the location of libraries is random and unknown to the script which doesn't allow autodetection.

**Comment by giannozz** [comment]
Please post issues to gitlab, not here (this is a mirror).  Please propose specific changes to autoconf under the form of a merge request. If you do not know how to do that, ask the people who put libraries in strange places: it's their fault, not ours.

**Comment by giannozz** [comment]
Actually, you may use environment variable FFT_LIBS, e.g. as in
   env FFT_LIBS=-lfftw3 ./configure ...
or something like that. It should not look for FFT libraries and accept what you pass.

**Comment by giannozz** [comment]
Well, not really: you still need to edit make.inc file, add  -D__FFTW3 to DFLAGS
