### ISSUE TITLE
About the pp.py

### ISSUE THREAD

**Issue by GJYAQXT** [QEF/q-e#29]
Why do I get an error Traceback (most recent call last) after using python pp.py:   File "pp.py", line 10, in <module>     user_input = raw_input ('Enter the prefix used for PH calculations (e.g. diam) \ n')NameError: name 'raw_input' is not defined?

**Comment by giannozz** [comment]
Please report bugs (or presumed such) on gitlab, maybe with some more detail

**Comment by hjunlee** [comment]
Dear GJYAQXT:

It seems that you have issues with importing raw_input and you are using the old version of pp.py. Could you try pp.py in the recent version of EPW? If you still have problems with using pp.py, please post your question with more details to the EPW forum (https://forum.epw-code.org/).

Sincerely,

H. Lee
