### ISSUE TITLE
dos.f90

### ISSUE THREAD

**Issue by giovannicantele** [QEF/q-e#3]
Line 160 of dos.f90 should be changed from
`Emax = MINVAL ( et(nbnd, 1:nks) )`
to
`Emax = MAXVAL ( et(nbnd, 1:nks) )`

If not set in the input of dos.x, the maximum energy is set to the minimum of the highest band otherwise and some of the expected dos is missing otherwise.

**Comment by giannozz** [comment]
Oops .. thank you, I'll fix it in the next merge request
