### ISSUE TITLE
Evaluation of dynamical matrix file for Al

### ISSUE THREAD

**Issue by jakobkraus** [QEF/q-e#30]
Hi,

I've successfully completed phonon calculations for several systems, including Al, Si, AlN, etc.
However, if I want to evaluate the dynamical matrix output files (called 'dmat.out' here)  with dynmat.x in order to get the IR/Raman spectra, I receive the following error, and only with Al (for the other systems, my script works fine):

At line 111 of file dynmat_sub.f90 (unit = 1, file = 'dmat.out')
Fortran runtime error: Bad real number in item 1 of list input

Error termination. Backtrace:
#0  0x7f4ea73778b0 in ???
#1  0x7f4ea7378395 in ???
#2  0x7f4ea7378b1a in ???
#3  0x7f4ea7567f28 in ???
#4  0x7f4ea756a32d in ???
#5  0x7f4ea756b8f9 in ???
#6  0x7f4ea7570a98 in ???
#7  0x556809b44890 in readmat2_
    at /home/kraus/q-e/LR_Modules/dynmat_sub.f90:111
#8  0x556809b31063 in dynmat
    at /home/kraus/q-e/PHonon/PH/dynmat.f90:175
#9  0x556809b3083e in main
    at /home/kraus/q-e/PHonon/PH/dynmat.f90:73

my script for dynmat.x was the following:

&INPUT
    fildyn  =   'dmat.out'
    asr     =   'no'
/

I've also attached the dmat.out file for Al in the dmat.zip directory.
[dmat.zip](https://github.com/QEF/q-e/files/4592390/dmat.zip)

I hope you can help me with this, and I am very grateful for your time and hard work.

Best regards,

Jakob

**Comment by giannozz** [comment]
I have opened an issue on gitlab: https://gitlab.com/QEF/q-e/-/issues/182 (issues should be posted there, not here)
