### ISSUE TITLE
QE-6.5 with Catalina

### ISSUE THREAD

**Issue by ronBirke** [QEF/q-e#31]
I can't get QE-6.5 to configure on MOS Catalina 15.5.5. Stops at configure: error: Fortran compiler cannot create executables. However, gfortran is in /usr/local/bin/gfortran. X-code 11.5 with command tools is loaded.

**Comment by giannozz** [comment]
Please report issues on gitlab, not on github (this is used as a mirror). Please also note that it is not the task of QE developers to fix broken software stacks as often found on Mac.
