### ISSUE TITLE
mpirun was unable to find the specified executable file

### ISSUE THREAD

**Issue by McAlexDudu** [QEF/q-e#32]
I install qe on the centos7, but when I test the 'pwscf.in' file, I got the wrong message. Do I forget to configure something?

$ mpirun -n 4 pw.x < pwscf.in |tee pwscf.out
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       731-sc
Executable: pw.x
--------------------------------------------------------------------------
4 total processes failed to start

**Comment by giannozz** [comment]
Please do not clutter the developers' space with trivial problems.
