### ISSUE TITLE
default ntyp maximum of 10 greatly limits calculations with specified initial magnetic order 

### ISSUE THREAD

**Issue by bernstei** [QEF/q-e#33]
I'm trying to do a collinear magnetic calculation with controlled but essentially random magnetic order.  The only way I've found to do this is to create one atomic type per atom, and give each one its own `starting_magnetization(i)`, but I quickly ran into the default maximum on `ntyp` of 10.  

This seems like a reasonably common use case, so I'm surprised it's not working.  Is there another way of doing this? If not, should the default maximum in `Modules/parameters.f95` be increased? 

[edited] The length of `atom_label` being 3 is also an issue, since even a 2-letter chemical symbol + 2 digit identifier is too long.

**Comment by giannozz** [comment]
Your case is not common at all. Anyway: you can edit Modules/parameters.f90 (not .f95) and increase ntypx, with little side effects (the many arrays of dimension ntypx take little memory; large arrays are dynamically allocated with the correct dimensions).

Please do not post issues or pull requests here: this is a mirror, the development is done on gitlab.

**Comment by bernstei** [comment]
On Oct 1, 2020, at 1:27 PM, giannozz <notifications@github.com<mailto:notifications@github.com>> wrote:

Your case is not common at all. Anyway: you can edit Modules/parameters.f90 (not .f95) and increase ntypx, with little side effects (the many arrays of dimension ntypx take little memory; large arrays are dynamically allocated with the correct dimensions).

Thanks.


Please do not post issues or pull requests here: this is a mirror, the development is done on gitlab.

Sorry, will do that next time.

**Comment by ltalirz** [comment]
@giannozz By the way, if you don't want people to open issues here, you can disable it in the settings of the repository:

![image](https://user-images.githubusercontent.com/1053245/105817374-d019c080-5fb5-11eb-9131-fa5257c449a9.png)

**Comment by ltalirz** [comment]
Also, you can add a web site to the "About" section
![image](https://user-images.githubusercontent.com/1053245/105817599-2129b480-5fb6-11eb-8b13-16cbb308a6f7.png)

It would probably make sense to put the link to the gitlab there
