### ISSUE TITLE
Error in documentation: 'termination' = 'interpolation'

### ISSUE THREAD

**Issue by chnyok** [QEF/q-e#4]
The PDF switches the "interpolation" keyword for "termination". The latter causes an input error that crashes turbo_spectrum.x

**Comment by giannozz** [comment]
Please report which PDF you are referring to. The only PDF in the documentation of TDDFPT is a paper, it can't be modified

**Comment by chnyok** [comment]
Yes, I am referring to that paper, which lists inputs in table B.2.

The program can be modified to accept (optionally) "terminator" instead of "interpolation".

Above, I mistakenly refer to "termination" instead of "terminator," the error was encountered with the latter, which is what appears in the paper.

**Comment by giannozz** [comment]
The reference input documentation is contained in files INPUT_Spectrum.*. That paper will be removed.
