### ISSUE TITLE
'cpp' shouldn't be used to preprocess fortran, use 'gcc -cpp' instead

### ISSUE THREAD

**Issue by yurivict** [QEF/q-e#8]
You use cpp to preprocess fortran files, for example:
```
cpp -fno-omit-frame-pointer -D__FFTW3 -I/usr/ports/science/quantum-espresso/work/q-e-qe-6.3/include -I/usr/ports/science/quantum-espresso/work/q-e-qe-6.3/FoX/finclude -I/usr/ports/science/quantum-espresso/work/q-e-qe-6.3/S3DE/iotk/include/ iotk_attr+COMPLEX1_0.f90 -o iotk_attr+COMPLEX1_0_tmp.f90 ;
```

In case of iotk_attr+COMPLEX1_0.f90 it damages the fortran syntax:
it converts
> call iotk_strcat(string,trim(adjustl(tmpval))//" ",ierr)

to

> call iotk_strcat(string,trim(adjustl(tmpval))

This perhaps happens only on FreeBSD for some reason, but this usage of ```cpp``` is invalid. You should use ```gcc -cpp```.

See the explanation in the gcc bug report that I've created: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86566

My original bug report: https://github.com/QEF/q-e/issues/7

**Comment by giannozz** [comment]
Oh, I see. The usage of cpp to preprocess fortran file is a relic of the past. All fortran compilers should be able by now to do preprocessing. For sure, gfortran does. In any case, once upon a time there was an option, "cpp --traditional" or something like that, preventing // to be recognized as comment.

**Comment by yurivict** [comment]
"cpp -P -traditional" works, thank you! You should add these flags to the cpp command by default.
I don't understand why doesn't it break on linux.

**Comment by giannozz** [comment]
I think it is the default: install/m4/x_ac_qe_cpp.m4, but maybe iotk (and FoX) use a different "configure" style

**Comment by yurivict** [comment]
FYI Somebody posted a message for my gcc bug report:
```
The proper way to preprocess Fortran code is with the Fortran
compiler.  You can and should use 'gfortran -cpp'.  See the
documentation that comes with your compiler.

If you think you need to use gcc, then you must use the
--tradition-cpp option.  The Fortran concatenation operator
// conflicts with modern C's comment delimiter //.
```

**Comment by giannozz** [comment]
Exactly so. With very few exceptions, likely obsolete, "configure" instructs fortran compilers to perform preprocessing.
